### ISSUE TITLE
A question about  'cpp_wrappers.cpp_neighbors.radius_neighbors'.

### ISSUE THREAD

**Issue by QWTforGithub** [overlappredator/OverlapPredator#20]
Hi,thanks for sharing the code.But I run the code encounters this question:

Connected to pydev debugger (build 201.6668.115)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qwt/code/OverlapPredator-main/datasets/dataloader.py", line 13, in <module>
    import cpp_wrappers.cpp_neighbors.radius_neighbors as cpp_neighbors
ModuleNotFoundError: No module named 'cpp_wrappers.cpp_neighbors.radius_neighbors'

I have compiled the C++ code, but the error still occurs.Is it about the path?
Thank you.

**Comment by ShengyuH** [comment]
maybe check this: https://github.com/overlappredator/OverlapPredator/issues/11#issue-856715691

**Comment by QWTforGithub** [comment]
> maybe check this: [#11 (comment)](https://github.com/overlappredator/OverlapPredator/issues/11#issue-856715691)

Thank you for your reply.I rewrote the setup.py file, republished it, and installed it again to fix the problem.

**Comment by lfxx** [comment]
> > maybe check this: [#11 (comment)](https://github.com/overlappredator/OverlapPredator/issues/11#issue-856715691)
> 
> Thank you for your reply.I rewrote the setup.py file, republished it, and installed it again to fix the problem.

Hello,i also encounter this problem,Cound please paste your setup.py file here to help me out?Thank you very much!
